[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "BANDSINTOWN_APP_ID"
  [build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/openai"
  to = "/.netlify/functions/openai"
  status = 200

[[redirects]]
  from = "/api/ticketmaster"
  to = "/.netlify/functions/ticketmaster"
  status = 200

[[redirects]]
  from = "/api/bandsintown/*"
  to = "/.netlify/functions/bandsintown"
  status = 200
  force = true

[[redirects]]
  from = "/api/guardian"
  to = "/.netlify/functions/guardian"
  status = 200

[[redirects]]
  from = "/api/tmdb/*"
  to = "/.netlify/functions/tmdb"
  status = 200
  force = true

[[redirects]]
  from = "/api/calendar"
  to = "/.netlify/functions/calendar"
  status = 200
